fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    apt: "puppetlabs/apt"
    chocolatey: "puppetlabs/chocolatey"
    zypprepo: "puppet/zypprepo"
    yumrepo_core:
      repo: "puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"

